## Week 2 tutorial 

Here is the practice problems for week 2. 

In [2]:
# Install packages
import numpy as np

In [3]:
# Create a numpy.ndarray with shape (3,) and set its elements to 1, 2, and 3, in that order.

my_list = [1, 2, 3]
my_array = np.array(my_list)
print(my_array)

[1 2 3]


In [4]:
# Create a numpy.ndarray with shape (3, 1) and set its elements to 1, 2, and 3, in that order.
my_array = np.array([[1, 2, 3]]).T # Here we transpose the array to ensure the shape is 3, 1 not 1, 3
print(my_array.shape)

(3, 1)


In [5]:
#Create a numpy.ndarray with shape (3, 2) and set the elements indexed by [:, 0] to 1, 2, and 3, and those indexed by [:, 1] to 4, 5, 6 in that order.
my_array=np.array([[1,2,3],[4,5,6]]).T
print(my_array.shape)

#Indexing
print(my_array[:, 0])
print(my_array[:, 1])

(3, 2)
[1 2 3]
[4 5 6]


In [6]:
#Create a numpy.ndarray with shape (4, 4) and set every element to 0 with data type int.
my_array = np.zeros((4, 4), dtype=int)
print(my_array)


[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [7]:
#Create a numpy.ndarray with shape (4, 4) and set every element to 1 data type float.
my_array = np.ones((4, 4), dtype=float)
print(my_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
#Create a numpy.ndarray that contains a sequence of 6 evenly spaced numbers starting with the float number 1.2 and ending with the float number 7.5.
my_array= np.linspace(1.2, 7.5, num=6)
print(my_array)

[1.2  2.46 3.72 4.98 6.24 7.5 ]


In [9]:
#Create a numpy.ndarray that contains the sequence of numbers starting with the int number 1 and ending with the int number 7 with every 2 increments included.
my_array= np.arange(1,7,2)
print(my_array)


[1 3 5]


In [10]:
# 
tmp = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(tmp)

x= tmp.T
print(x)

y= tmp.reshape(3, 4)
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  4  7 10]
 [ 2  5  8 11]
 [ 3  6  9 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
#For x and y defined in the following code chunk, compute their element-wise difference.

x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[5, 4, 3], [2, 1, 0]])

diff = x - y
print(diff)

[[-4 -2  0]
 [ 2  4  6]]


In [12]:
#Compute the matrix product of x and y.T.
y_transpose = y.T
m_product = np.dot(x, y_transpose)
print(m_product)

[[22  4]
 [58 13]]


In [13]:
#Use the function np.max() to compute the maximum value in the array x.
print(np.max(x))

6


In [14]:
#Use the numpy.ndarray method max() to return the maximum values along the first dimension in the array y.
print(max(y[0]))

5


In [15]:
#Compute the element-wise square root of the following array np.array([4, 33, 9]).
x = np.array([4,33,9])
print(np.sqrt(x))

[2.         5.74456265 3.        ]


In [16]:
x = np.random.randn(3, 4, 2)
y = np.ones(x.shape)

In [17]:
#Use slicing or indexing to return the first 2 elements of x in dimension 1, which should result in an array with shape equal to (2, 4, 2).
print(x[:2,:,:].shape)

(2, 4, 2)


In [18]:
# Use slicing or indexing to return the first element in x in dimension 1, the second element in dimension 2, and every element in dimension 3. Your result should be an array with shape equal to (2, ).
print(x.shape)
print(x[0,1,:].shape)


(3, 4, 2)
(2,)


In [19]:
# Concatenate x and y along the second dimension.
print(np.concatenate((x, y), 1).shape)


(3, 8, 2)


In [23]:
#Make a deep copy of x, add 10 to every element.
deep_x = np.array(x)+10
print(deep_x)

[[[10.55343467 11.11914555]
  [ 9.87360746  9.9609172 ]
  [ 9.11659656  9.10100844]
  [11.04040587  9.497036  ]]

 [[ 9.89648269 10.79268113]
  [10.05145772 10.91846221]
  [11.07003166 11.39335676]
  [10.61717148 11.59806532]]

 [[ 9.81765945  8.68988192]
  [10.31899466  8.09312267]
  [10.57888322  9.51748772]
  [10.12915069 11.36794453]]]


In [34]:
#Make a deep copy of x, set every element in the first dimension to zero.
# I think i fucked something up here
deep_x = np.array(x)
print(np.shape(deep_x))
print(deep_x)
deep_x = x[0,:,:]
print(np.shape(deep_x))
print(deep_x)

(3, 4, 2)
[[[ 0.          0.        ]
  [ 0.          0.        ]
  [ 0.          0.        ]
  [ 0.          0.        ]]

 [[-0.10351731  0.79268113]
  [ 0.05145772  0.91846221]
  [ 1.07003166  1.39335676]
  [ 0.61717148  1.59806532]]

 [[-0.18234055 -1.31011808]
  [ 0.31899466 -1.90687733]
  [ 0.57888322 -0.48251228]
  [ 0.12915069  1.36794453]]]
(4, 2)
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [39]:
# Make a deep copy of x, use boolean indexing to set every element of x that is less than 0.5 to zero.
deep_x = np.array(x)
print(deep_x)
deep_x[deep_x < 0.5] = 0 # If the value is less than 0.5, set it to 0
print(deep_x)


[[[ 0.          0.        ]
  [ 0.          0.        ]
  [ 0.          0.        ]
  [ 0.          0.        ]]

 [[-0.10351731  0.79268113]
  [ 0.05145772  0.91846221]
  [ 1.07003166  1.39335676]
  [ 0.61717148  1.59806532]]

 [[-0.18234055 -1.31011808]
  [ 0.31899466 -1.90687733]
  [ 0.57888322 -0.48251228]
  [ 0.12915069  1.36794453]]]
[[[0.         0.        ]
  [0.         0.        ]
  [0.         0.        ]
  [0.         0.        ]]

 [[0.         0.79268113]
  [0.         0.91846221]
  [1.07003166 1.39335676]
  [0.61717148 1.59806532]]

 [[0.         0.        ]
  [0.         0.        ]
  [0.57888322 0.        ]
  [0.         1.36794453]]]
